baseURL = 'https://visitcobblestonelake.com/'
languageCode = 'en-us'
title = 'Cobblestone Lake'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = 'Info'
    url = '/info/'
    weight = 1
  [[menu.main]]
    name = 'Contact Us'
    url = '/contact-us/'
    weight = 2
  [[menu.main]]
    name = 'Lot Pricing'
    url = '/lot-pricing/'
    weight = 3
  [[menu.main]]
    name = 'Covenants and Plat'
    url = '/covenants-and-plat/'
    weight = 4 