# Base settings
baseURL       = "https://jddies.github.io/cobblestonelake/"
languageCode  = "en-us"
title         = "Cobblestone Lake Subdivision"
theme         = "ananke"
relativeURLs  = true
canonifyURLs  = true
pagination = { pagerSize = 10 }


# Site‑wide parameters
[params]
  # Path is relative (no leading slash) so Hugo will emit ./images/banner.jpg under your baseURL
  featured_image = "images/banner.jpg"
  # Optional subtitle/description
  description    = "Cobblestone Lake has a wonderful 5‑acre private lake with 2‑acre lots for sale."

# Main navigation menu
[menu]

  [[menu.main]]
    identifier = "view-lots"
    name       = "View Lots"
    url        = "/lots/"
    weight     = 1

  [[menu.main]]
    identifier = "community-rules"
    name       = "Community Rules"
    url        = "/community-rules/"
    weight     = 2

  [[menu.main]]
    identifier = "contact"
    name       = "Contact Us"
    url        = "/contact/"
    weight     = 3
[markup.goldmark.renderer]
unsafe = true